Hometask 1
AnnaBodrova/Teamcity-tests pull request #1
Opened 2023-12-05 06:12 UTC by AnnaBodrova

2023-12-08 19:11 UTC, AlexPshe requested changes
Привет!

Большое спасибо за качественное выполнение задания!

Я добавила несколько комментов по улучшению - нужно пофиксить их за неделю и будет зачтено ⚡️

2023-12-08 19:11 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/BuildConfigurationTest.java
> +        soft.assertThat(buildConfig.getId()).isEqualTo(testData.getBuildType().getId());
Выглядит как очень большое количество полей по которым нужно проходиться) 

А можем ли мы сравнить два обьекта на равенство `buildConfig` и `testData.getBuildType()` вместо перечисления всех полей?

2023-12-08 19:11 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/BuildConfigurationTest.java
> +        testData.getBuildType().getSteps().getStep().get(0).setName(" !\"#$%&\\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\\\]^_`abcdefghijklmnopqrstuvwxyz{|}~");
Думаю, стоит вынести в отдельную константу перечисление всех доступных символов

2023-12-08 19:11 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/BuildConfigurationTest.java
> +        var buildtype = new UncheckedBuildConfig(Specifications.getSpec().authSpec(testData.getUser()))
Выглядит как использование `CheckedBuildConfig`, можем ли на него заменить?

2023-12-08 19:11 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/BuildConfigurationTest.java
> +        var buildtype = new UncheckedBuildConfig(Specifications.getSpec().authSpec(testData.getUser()))
И во всех других местах 🙌

2023-12-08 19:11 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/BuildConfigurationTest.java
> +
Форматинг: удалить строки

2023-12-08 19:11 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/RolesTest.java
Форматинг: пустая строка

2023-12-12 10:17 UTC, AnnaBodrova commented on src/test/java/com/example/teamcity/api/BuildConfigurationTest.java
> +        soft.assertThat(buildConfig.getId()).isEqualTo(testData.getBuildType().getId());
@AlexPshe дело в том, что `testData.getBuildType()` содержит в себе parentProject, а `buildConfig`, который из ответа не содержит.

2023-12-12 10:39 UTC, AnnaBodrova commented on src/test/java/com/example/teamcity/api/BuildConfigurationTest.java
> +        soft.assertThat(buildConfig.getId()).isEqualTo(testData.getBuildType().getId());
но можно сравнить некоторые объекты внутри, и тем самым тоже уменьшить кол-во сравнений))

2023-12-17 14:22 UTC, AlexPshe approved these changes
Отлично, все зачтено!

2023-12-17 14:36 UTC, merged